apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-server-argo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    
spec:
  project: default

  source:
    repoURL: https://github.com/rsship/argomaton.git 
    targetRevision: HEAD  
    path: myapp

  destination:
    server: https://kubernetes.default.svc
